export const validationRules = {
  required: (field: string) => `${field} is required`,
  min: (field: string, min: number) => `${field} must be at least ${min}`,
  max: (field: string, max: number) => `${field} must be at most ${max}`,
  minLength: (field: string, min: number) => `${field} must be at least ${min} characters`,
  maxLength: (field: string, max: number) => `${field} must be at most ${max} characters`,
  email: (field: string) => `${field} must be a valid email address`,
  phone: (field: string) => `${field} must be a valid phone number`,
  url: (field: string) => `${field} must be a valid URL`,
  pattern: (field: string, pattern: RegExp) => `${field} format is invalid`,
  equal: (field: string, other: string) => `${field} must match ${other}`,
  unique: (field: string) => `${field} must be unique`,
  exists: (field: string) => `${field} already exists`,
  notFound: (field: string) => `${field} not found`,
  invalid: (field: string) => `${field} is invalid`,
  notEmpty: (field: string) => `${field} cannot be empty`,
  numeric: (field: string) => `${field} must be a number`,
  integer: (field: string) => `${field} must be an integer`,
  positive: (field: string) => `${field} must be positive`,
  negative: (field: string) => `${field} must be negative`,
  range: (field: string, min: number, max: number) => 
    `${field} must be between ${min} and ${max}`,
  date: (field: string) => `${field} must be a valid date`,
  future: (field: string) => `${field} must be in the future`,
  past: (field: string) => `${field} must be in the past`,
  boolean: (field: string) => `${field} must be a boolean`,
  array: (field: string) => `${field} must be an array`,
  object: (field: string) => `${field} must be an object`,
};

export const validationPatterns = {
  email: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  phone: /^\+?[\d\s-()]{10,}$/,
  url: /^https?:\/\/[^\s/$.?#].[^\s]*$/,
  password: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$/,
  username: /^[a-zA-Z0-9_-]{3,20}$/,
  color: /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/,
  ip: /^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$/,
  uuid: /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
  date: /^\d{4}-\d{2}-\d{2}$/,
  time: /^\d{2}:\d{2}(:\d{2})?$/,
  datetime: /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}(:\d{2})?$/,
  zipcode: /^\d{5}(-\d{4})?$/,
  creditCard: /^\d{4}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}$/,
};
