apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  firebase-api-key: "your-firebase-api-key"
  firebase-auth-domain: "your-firebase-auth-domain"
  firebase-project-id: "your-firebase-project-id"
  firebase-storage-bucket: "your-firebase-storage-bucket"
  firebase-messaging-sender-id: "your-firebase-messaging-sender-id"
  firebase-app-id: "your-firebase-app-id"
